[build]
  command = """
    npm install --force
    npx msw init ./build --save
    echo -e "REACT_APP_GITHUB_AUTH_URL=${{secrets.REACT_APP_GITHUB_AUTH_URL}}\n
                    REACT_APP_KAKAO_AUTH_URL=${{secrets.REACT_APP_KAKAO_AUTH_URL}}\n
                    REACT_APP_NAVER_AUTH_URL=${{secrets.REACT_APP_NAVER_AUTH_URL}}\n
                    REACT_APP_PUBLIC_URL=${{secrets.REACT_APP_PUBLIC_URL}}\n
                    REACT_APP_UNIVERSAL_LINK=${{secrets.REACT_APP_UNIVERSAL_LINK}}\n" > ./.env
  """
  publish = "build"