name: Auto Deploy after push

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name : Docker Environment Varibale File 
        run: echo -e "REACT_APP_GITHUB_AUTH_URL=${{secrets.REACT_APP_GITHUB_AUTH_URL}}\n
                      REACT_APP_KAKAO_AUTH_URL=${{secrets.REACT_APP_KAKAO_AUTH_URL}}\n
                      REACT_APP_NAVER_AUTH_URL=${{secrets.REACT_APP_NAVER_AUTH_URL}}\n
                      REACT_APP_PUBLIC_URL=${{secrets.REACT_APP_PUBLIC_URL}}\n
                      REACT_APP_UNIVERSAL_LINK=${{secrets.REACT_APP_UNIVERSAL_LINK}}\n" > ./.env
      
      - name: Install npm package
        run: npm install --force
    
      - name: Build
        run: npm run build

      - name: Make mockServiceWorker.js
        run: npx msw init ./build --save